# 开发环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:postgresql://localhost:5432/blog
    username: postgres
    password: Shicong666
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA 配置
  jpa:
    hibernate:
      ddl-auto: update  # 开发环境自动更新表结构
    show-sql: true  # 显示 SQL 语句
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # 格式化 SQL
        use_sql_comments: true  # 显示 SQL 注释
    open-in-view: false

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 16379
      password: 
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# Sa-Token 配置
sa-token:
  # token 临时有效期（单位：秒），30分钟无操作则过期，有操作则自动续签
  active-timeout: 1800
  # Redis 配置
  alone-redis:
    database: 1
    host: localhost
    port: 16379
    password: 
    timeout: 10s

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 日志配置
logging:
  level:
    com.cleveronion.blog: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/cleveronion-blog-dev.log

# GitHub OAuth2 配置（开发环境）
github:
  oauth2:
    client-id: Ov23lidYpkQFTdG7UseL
    client-secret: ab1bc714224d8425f4aeb0237a225746162b3ca2
    redirect-uri: http://localhost:3000/auth/callback
    authorize-url: https://github.com/login/oauth/authorize
    access-token-url: https://github.com/login/oauth/access_token
    user-info-url: https://api.github.com/user

# 前端配置
frontend:
  base-url: http://localhost:3000
  auth:
    callback-path: /auth/callback
    error-path: /auth/error

# 管理员配置
admin:
  github-ids:
    - 152043550  # 示例管理员GitHub ID，请替换为实际的GitHub ID
    # - 987654321  # 可以配置多个管理员
  allow-credentials: true
  max-age: 3600